torchrun --nproc_per_node=2 --master_port=1234 run_pretrain.py \
--batch_size=128 \
--hidden_size=128 \
--num_hidden_layers=2 \
--num_attention_head=2 \
--epoch=20 \
--max_seq_length=50 \
--data_name='amazon' \
--strd_ym='202312' \
--shaply_value='y' \
--hierarhical='y' \
--lr=0.001 \
--profile_yn='n'
